# version: '3.9'

# networks:
#   my_inception:

# services:
#   mariadb:
#     build: ./requirements/mariadb/.
#     container_name: mariadb
#     restart: on-failure
#     networks:
#       - my_inception
#     env_file:
#       - .env
#   nginx:
#     build: ./requirements/nginx/.
#     container_name: nginx
#     restart: on-failure
#     ports:
#       - 443:443
#     networks:
#       - my_inception
#     depends_on:
#       - wordpress
#     env_file:
#       - .env
#   wordpress:
#     build: ./requirements/wordpress/.
#     container_name: wordpress
#     restart: on-failure
#     networks:
#       - my_inception
#     depends_on:
#       - mariadb
#     env_file:
#       - .env


version: '3.9'

networks:
  my_inception:


services:
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    restart: on-failure
    networks:
      - my_inception
    env_file:
      - .env
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    restart: on-failure
    ports:
      - 443:443
    networks:
      - my_inception
    depends_on:
      - wordpress
    env_file:
      - .env
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    restart: on-failure
    networks:
      - my_inception
    depends_on:
      - mariadb
    env_file:
      - .env
