version: '3'

networks:
  inception:

volumes:
  my_db:
    driver_opts:
     type: none
     o: bind
     device: /home/kali/data/mariadb
  my_wp:
    driver_opts:
      type: none
      o: bind
      device: /home/kali/data/wordpress

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - my_db:/var/lib/mysql
    networks:
      - inception
  
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - my_wp:/var/www/html/wordpress
    networks:
      - inception
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - my_wp:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception

#version: '3.9'
#
#networks:
#  my_inception:
#
#
#services:
#  mariadb:
#    build: ./requirements/mariadb/.
#    container_name: mariadb
#    restart: on-failure
#    networks:
#      - my_inception
#    env_file:
#      - .env
#  nginx:
#    build: ./requirements/nginx/.
#    container_name: nginx
#    restart: on-failure
#    ports:
#      - 443:443
#    networks:
#      - my_inception
#    depends_on:
#      - wordpress
#    env_file:
#      - .env
#  wordpress:
#    build: ./requirements/wordpress/.
#    container_name: wordpress
#    restart: on-failure
#    networks:
#      - my_inception
#    depends_on:
#      - mariadb
#    env_file:
#      - .env
