version: '3'

networks:
  inception:

# volumes:
#   my_db:
#     driver_opts:
#      type: none
#      o: bind
#      device: /home/kali/data/mariadb
#   my_wp:
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/kali/data/wordpress
volumes:
  my_db:
    driver_opts:
     type: none
     o: bind
     device: Users/amessah/data/mariadb
  my_wp:
    driver_opts:
      type: none
      o: bind
      device: Users/amessah/data/wordpress
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - my_db:/var/lib/mysql
    networks:
      - inception
  
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - my_wp:/var/www/html/wordpress
    networks:
      - inception
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - my_wp:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception
  adminer:
    build: ./requirements/bonus/adminer/.
    container_name: adminer
    restart: on-failure
    ports:
      - 8081:8080
    networks:
      - inception
    volumes:
      - my_db:/var/lib/mysql
  cadvisor:
    build: ./requirements/bonus/cadvisor/.
    container_name: cadvisor
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/snap/docker/common/var-lib-docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
  static_website:
    build: ./requirements/bonus/static_website/.
    container_name: static_website
    restart: on-failure
    ports:
      - 1337:80
    networks:
      - inception
