FROM debian:bullseye

RUN apt-get update && apt-get install php php-fpm php-mysql wget -y

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

RUN chmod +x wp-cli.phar

RUN mv wp-cli.phar /usr/local/bin/wp

COPY config.sh .

RUN chmod +x config.sh

RUN mkdir -p /var/wwww/html/wordpress

EXPOSE 9000

ENTRYPOINT ["./config.sh"]

#CMD [ "bash", "./config.sh" ]

CMD ["/usr/sbin/php-fpm7.4", "-F""]
